name: Upload Portenta X8 image pre-release

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  GetVersions:
    uses: ./.github/workflows/foundries-target.yml
    with:
      factory: arduino
      branch: main
      environment: staging
    secrets: inherit

  UploadPreRelease:
    needs: [GetVersions]
    uses: ./.github/workflows/foundries-prerelease.yml
    if: ${{ needs.GetVersions.outputs.factory-version != needs.GetVersions.outputs.bucket-version }}
    with:
      factory: arduino
      branch: main
      target-version: ${{ needs.GetVersions.outputs.factory-version }}
      artifacts: "portenta-x8-mfgtools/artifacts/mfgtool-files-portenta-x8.tar.gz,portenta-x8/artifacts/imx-boot-portenta-x8,portenta-x8/artifacts/u-boot-portenta-x8.itb,portenta-x8/artifacts/sit-portenta-x8.bin,assemble-system-image/artifacts/main/lmp-factory-image-portenta-x8.wic.gz"
      slack-message: Portenta X8 target version ${{ needs.GetVersions.outputs.factory-version }} is available for testing
      environment: staging
    secrets: inherit
