name: Promote Portenta X8 image pre-release

on:
  workflow_dispatch:
    inputs:
      target-version:
        description: 'Target version to promote'
        required: true
        type: string

jobs:
  Promote:
    uses: ./.github/workflows/foundries-promote.yml
    with:
      target-version: ${{ inputs.target-version }}
      environment: staging
      slack-message: "Foundries Factory Target version ${{ inputs.target-version }} has been promoted to production"
    secrets: inherit
